package com.javaclimb.mapper;

import com.javaclimb.entity.CartInfo;
import org.springframework.stereotype.Repository;

@Repository
public interface CartInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_info
     *
     * @mbg.generated
     */
    int insert(CartInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_info
     *
     * @mbg.generated
     */
    int insertSelective(CartInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_info
     *
     * @mbg.generated
     */
    CartInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CartInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CartInfo row);
}