package com.javaclimb.mapper;

import com.javaclimb.entity.CommentInfo;
import org.springframework.stereotype.Repository;

@Repository
public interface CommentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbg.generated
     */
    int insert(CommentInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbg.generated
     */
    int insertSelective(CommentInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbg.generated
     */
    CommentInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CommentInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(CommentInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CommentInfo row);
}