package com.javaclimb.mapper;

import com.javaclimb.entity.TypeInfo;
import org.springframework.stereotype.Repository;

@Repository
public interface TypeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbg.generated
     */
    int insert(TypeInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbg.generated
     */
    int insertSelective(TypeInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbg.generated
     */
    TypeInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TypeInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TypeInfo row);
}